title: "Patrick Schneider | Data & Cloud Engineer"
description: >
  Portfolio showcasing AI, Cloud, and Quality Systems projects at Schreiber Foods
  and Grand Valley State University (MACS).
url: "https://patrickschneider.github.io"
theme: minima

author:
  name: "Patrick Schneider"
  email: "schnepat@mail.gvsu.edu"
  linkedin: "https://www.linkedin.com/in/patrick-schneider-7919b050"
  github: "https://github.com/patrickschneider"

navbar:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
