title: "Patrick Schneider | Data & Cloud Engineer"
description: >
  Portfolio showcasing AI, Cloud, and Quality Systems projects at Schreiber Foods
  and Grand Valley State University (MACS).
url: "https://patrickschneider.github.io"
theme: minima

author:
  name: "Patrick Schneider"
  email: "patrickschneider@email.com"
  linkedin: "https://linkedin.com/in/patrickschneider"
  github: "https://github.com/patrickschneider"

# Navigation links for all pages
navbar:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed
